name: Update Debian Changelog

on:
  release:
    types: [published]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Debian Tools
        run: sudo apt-get install devscripts

      - name: Run Update Script
        run: |
          chmod +x ./debian/update-changelog.sh
          ./debian/update-changelog.sh ${{ github.ref_name }} "New release ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_GITHUB_ACTIONS }}

      - name: Push Changes
        run: |
          git config --global user.name 'Rumen Paletov'
          git config --global user.email 'rumen.paletov@gmail.com'
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_GITHUB_ACTIONS }}
